name:
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - altair=4.1
  - git-lfs
  - importlib_resources
  - jupyter
  - jupyter_contrib_nbextensions
  - jupyterlab
  - jupytext
  - lifelines
  - natsort
  - nodejs
  - pip
  - python=3.8
  - scikit-learn
  - seaborn=0.11.1
  - snakemake=6.2.1
  - sra-tools=2.10.9
  - pip:
    - dms-variants==1.4.0
    - dmslogo==0.6.2
    - openpyxl
    - pdb_prot_align
